spring.application.name=product
server.port=8081

# --- BASE DE DATOS ---
spring.datasource.url=${DB_URL:jdbc:postgresql://db.vjimgzqcvmevoqorpkfk.supabase.co:6543/postgres?prepareThreshold=0}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- HIBERNATE ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- JWT Y SEGURIDAD ---
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# --- CORS Y RED ---
app.cors.allowed-origin=${FRONTEND_URL:http://localhost:5173}
server.forward-headers-strategy=framework

# --- JACKSON (Serialización) ---
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss.SSSSSS
spring.jackson.deserialization.fail-on-unknown-properties=true