spring.application.name=product

# Puerto donde se ejecutará la aplicación
server.port=8081

#-----------------------------------------------#
# Configuración de la base de datos con Supabase
#-----------------------------------------------#

# Conexión a la base de datos PostgreSQL en Supabase
spring.datasource.url=jdbc:postgresql://db.vjimgzqcvmevoqorpkfk.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#----------------------------#
# CONFIGURACIÓN DE HIBERNATE
#----------------------------#

# Update crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#-------------------#
# CONFIGURACIÓN JWT
#------CONFIGURACIÓN#

# Guardada en una variable de entorno, en caso de necesitarla comuniquese con Jaime Hermosilla
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
app.cors.allowed-origin=http://localhost:5173