spring.application.name=user
server.port=8080

# --- BASE DE DATOS ---
spring.datasource.url=${DB_URL:jdbc:postgresql://db.vjimgzqcvmevoqorpkfk.supabase.co:6543/postgres?prepareThreshold=0}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- JWT Y SEGURIDAD ---
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
# Dinámico: CORS para React
app.cors.allowed-origin=${FRONTEND_URL:http://localhost:5173}

server.forward-headers-strategy=framework

# MAIL / SMTP CONFIGURATION (RESEND)
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# El correo de Resend
app.mail.from=onboarding@resend.dev