spring.application.name=user

#-----------------------------------------------#
# Configuración de la base de datos con Supabase
#-----------------------------------------------#

# Conexión a la base de datos PostgreSQL en Supabase
spring.datasource.url=jdbc:postgresql://db.vjimgzqcvmevoqorpkfk.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#-------------------#
# Configuracion JWT
#-------------------#

# Guardada en una variable de entorno, en caso de necesitarla comuniquese con Jaime Hermosilla
jwt.secret=${JWT_SECRET}
# Tiempo de expiración del token en milisegundos (ejemplo: 24 horas = 86400000 ms)
jwt.expiration=86400000

# Frontend React permitido para CORS
app.cors.allowed-origin=http://localhost:5173