spring.application.name=order

# El puerto de este microservicio será el 8082
server.port=8082

#-----------------------------------------------#
# Configuración de la base de datos con Supabase
#-----------------------------------------------#
spring.datasource.url=jdbc:postgresql://db.vjimgzqcvmevoqorpkfk.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#----------------------------#
# CONFIGURACIÓN DE HIBERNATE
#----------------------------#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#-------------------#
# CONFIGURACIÓN JWT
#-------------------#
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Frontend React permitido para CORS
app.cors.allowed-origin=http://localhost:5173

# Timeouts: Si el otro servicio no responde en 5 segundos, abortamos para no colgarnos
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000

# URL del microservicio de productos
app.clients.product-service.url=http://localhost:8081