version: '3.8'

services:

  # SERVICIO DE GATEWAY
  gateway-service:
    build: ./ruki-gateway
    ports:
      - "8000:8000"
    networks:
      - ruki-network
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - USER_SERVICE_URL=http://usuarios-service:8080
      - PRODUCT_SERVICE_URL=http://productos-service:8081
      - ORDER_SERVICE_URL=http://pedidos-service:8082
      - PAYMENT_SERVICE_URL=http://pagos-service:8083
    restart: unless-stopped

  # MICROSERVICIO DE USUARIOS
  usuarios-service:
    build: ./user
    networks:
      - ruki-network
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    restart: unless-stopped

  # MICROSERVICIO DE PRODUCTOS
  productos-service:
    build: ./product
    networks:
      - ruki-network
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
    restart: unless-stopped

  # MICROSERVICIO DE PEDIDOS
  pedidos-service:
    build: ./order
    networks:
      - ruki-network
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - PRODUCT_SERVICE_URL=http://productos-service:8081
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - USER_SERVICE_URL=http://usuarios-service:8080
    restart: unless-stopped

  # MICROSERVICIO DE PAGOS
  pagos-service:
    build: ./payment
    networks:
      - ruki-network
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - ORDER_SERVICE_URL=http://pedidos-service:8082
      - PAYMENT_SERVICE_URL=http://pagos-service:8083
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    restart: unless-stopped

networks:
  ruki-network:
    driver: bridge