# El puerto del microservicio de Pagos
server.port=8083
spring.application.name=payment

# --- BASE DE DATOS ---
spring.datasource.url=${DB_URL:jdbc:postgresql://db.vjimgzqcvmevoqorpkfk.supabase.co:5432/postgres}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

app.clients.order-service.url=${ORDER_SERVICE_URL:http://localhost:8082}
app.payments.base-url=http://137.184.109.26:8000
app.cors.allowed-origin=${FRONTEND_URL:http://localhost:5173}

server.forward-headers-strategy=framework

# --- STRIPE CONFIGURATION ---
stripe.api.key=${STRIPE_SECRET_KEY}

# URL del frontend para que Stripe redirija al usuario al terminar
app.frontend.url=${FRONTEND_URL:http://localhost:5173}

stripe.webhook.secret=whsec_tu_secreto_de_prueba_aqui
