# El puerto del microservicio de Pagos
server.port=8083
spring.application.name=payment

# --- BASE DE DATOS ---
spring.datasource.url=${DB_URL:jdbc:postgresql://db.vjimgzqcvmevoqorpkfk.supabase.co:5432/postgres}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

app.clients.order-service.url=${ORDER_SERVICE_URL:http://localhost:8082}
app.payments.base-url=${PAYMENT_SERVICE_URL:http://localhost:8083}

server.forward-headers-strategy=framework