server.port=8083
spring.application.name=payment

# --- BASE DE DATOS ---
spring.datasource.url=${DB_URL:jdbc:postgresql://db.vjimgzqcvmevoqorpkfk.supabase.co:6543/postgres?prepareThreshold=0}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

# --- HIBERNATE  ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- COMUNICACIÓN Y RED ---
app.clients.order-service.url=${ORDER_SERVICE_URL:http://localhost:8082}
app.payments.base-url=http://137.184.109.26:8000
app.cors.allowed-origin=${FRONTEND_URL:http://localhost:5173}
server.forward-headers-strategy=framework

# --- STRIPE CONFIGURATION ---
stripe.api.key=${STRIPE_SECRET_KEY:key-test}
app.frontend.url=${FRONTEND_URL:http://localhost:5173}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:secret_test}

# --- JWT Y SEGURIDAD ---
jwt.secret=${JWT_SECRET:jwt_test}
jwt.expiration=86400000

# --- JACKSON ---
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss.SSSSSS
spring.jackson.deserialization.fail-on-unknown-properties=true